version: '3'
services:
  db:
    image: mysql:5.7
    container_name: fox_library_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'foxlibrary_db'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 'foxlibrary'
      MYSQL_PASSWORD: 'F0xL1br2ry'
    ports:
      - "6033:3306"
    volumes:
      - fox-db:/var/lib/mysql
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
volumes:
  fox-db:
