server:
  port: 5000

spring:
  application:
    name: foxlibrary
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jmx:
    enable: false
  database:
    url: jdbc:mysql://localhost:6033/foxlibrary?useTimezone=true&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: foxlibrary
    password: F0xL1br2ry
    validationQuery: SELECT 1