spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:6033/foxlibrary_db?useTimezone=true&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&sslMode=DISABLED
    driverClassName: com.mysql.cj.jdbc.Driver
    password: F0xL1br2ry
    validationQuery: SELECT 1
    username: foxlibrary
  jmx:
    enable: 'false'
  application:
    name: foxlibrary
flyway:
  url: jdbc:mysql://localhost:6033/foxlibrary_db?useTimezone=true&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&sslMode=DISABLED
  username: foxlibrary
  password: F0xL1br2ry